

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import store from "@/Utils/ProviderStore";
import NavSidePopup from "@/app/NavBar/NavSidePopup";
import { Provider } from "react-redux";
import {AppProvider} from "@/Utils/AppProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)


{
  return (
    <html lang="en">
    <head>
      <title>My Next.js App</title>
      <meta name="description" content="A description of your app" />
    </head>
    <body>
        <AppProvider>
        <nav className="w-full p-2 sticky">
          <NavSidePopup
          />
          </nav>
          <div className="w-full h-full">
        {children}
        </div>
        </AppProvider>
     </body>
     </html>
  );
}
